### ISSUE TITLE
Why vm.Script over eval?

### ISSUE THREAD

**Issue by lukechilds** [timneutkens/is-async-supported#1]
I'm sure there's a reason, but not sure what?

Using `eval` would work in the browser too.

**Comment by timneutkens** [comment]
I'll have to check, But I believe it didn't work Cause the parser would kill it. I'll check when i get home!

**Comment by lukechilds** [comment]
Hmmn, works for me:
Node.js 8: `true`
Chrome: `true`
Node.js 4: `false`
Safari: `false`

`¯\_(ツ)_/¯`

Submitted a PR.

**Comment by timneutkens** [comment]
@rauchg @leo Since most ZEIT stuff Depends on this :)

**Comment by lukechilds** [comment]
Just going through all my old open PRs.

Is there any interest in merging this or should I close it?

**Comment by timneutkens** [comment]
Commented on the PR 👍
